[package]
name = "occ-raycasting-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
occ-raycasting = { path = "../occ-raycasting" }
pretty_env_logger = "0.5"
log = "0.4"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
glob = "0.3"
